### ISSUE TITLE
Only one changeset detail available on build summary page

### ISSUE THREAD

**Issue by gromhit** [jenkinsci/liquibase-runner-plugin#12]
If a run several changeset in the same job (several users), i can see all scripts played on summary page but when i click on details i only the first is available and the others are on errors.

files = findFiles(glob: "${mainLivPath}/Liquibase/**/main_changelog.xml")
for (liqInd = 0; liqInd < files.size(); liqInd++){
	dir= files[liqInd].path.minus("main_changelog.xml")
	liquibaseUpdate(basePath :"${dir}",
			changeLogFile: "main_changelog.xml",
			classpath: "${mainLivPath}/Liquibase/lib/ojdbc6.jar",
			driverClassname: 'oracle.jdbc.driver.OracleDriver',
			liquibasePropertiesPath: "${dir}/liquibase.preliv-database.properties",
			contexts: 'standard',
			label: '${dir}'
	)
}

![image](https://user-images.githubusercontent.com/31438895/33887781-3f0715a4-df4b-11e7-9f81-2e94e5038d3b.png)
![image](https://user-images.githubusercontent.com/31438895/33887859-80ecb35c-df4b-11e7-9d3c-4c224c1c6790.png)
![image](https://user-images.githubusercontent.com/31438895/33887903-aa368b84-df4b-11e7-9fa6-18617b5d0955.png)

Do i have to add a publishHTML step before each run ? If yes, where are the HTML reports to publish ?

Thanks for your help.
Regards.
Jerome.

**Comment by robertericreeves** [comment]
We changed the Liquibase Runner Plugin for 1.3.0 significantly. That should resolve this issue.

**Comment by robertericreeves** [comment]
We changed the Liquibase Runner Plugin for 1.3.0 significantly. That should resolve this issue.
