### ISSUE TITLE
How soon can we expect 1.4.3 to be available in the Jenkins plugin manager?

### ISSUE THREAD

**Issue by O5ten** [jenkinsci/liquibase-runner-plugin#19]
@r2datical Just the question in the topic.

**Comment by r2datical** [comment]
We're getting past a security issue that caused the plugin to be unpublished. We're working through that now. I've got a new PR to get us past it. I'll update this issue the second I get an update. Thanks!

**Comment by O5ten** [comment]
Thank you for the response @r2datical, please keep this issue open until there's a release in case somebody else comes looking for it here. :)

**Comment by robertericreeves** [comment]
1.4.10 is released. Thanks!
