### ISSUE TITLE
Liquibase Defaults File Does not work

### ISSUE THREAD

**Issue by emoshaya-cognito** [jenkinsci/liquibase-runner-plugin#8]
I put aws.properties in this field and it's available in the slave workspace. However I get the bellow error... Any ideas?

![liquibase2](https://cloud.githubusercontent.com/assets/8818542/14935464/3a2e03c4-0eca-11e6-8cef-691bfc18dce1.png)

![liquibase](https://cloud.githubusercontent.com/assets/8818542/14935455/10d81d7a-0eca-11e6-9b07-33bf660f2026.png)

**Comment by prospero238** [comment]
I can confirm this.  The Jenkins file abstraction isn't used during properties loading.

A fix will be quickly published.

**Comment by prospero238** [comment]
Fix resides in 1.0.2.  It has been published to artifactory, and will be available as an update once Jenkins Update Center updates.
