### ISSUE TITLE
evaluated changeset not found

### ISSUE THREAD

**Issue by emoshaya** [jenkinsci/liquibase-runner-plugin#9]
Hi I have successfully ran liquibase update using your plugin. However, when I click on the changeset in the build. It reports a 404 not found. Please see screenshots:

![image](https://cloud.githubusercontent.com/assets/8818542/16673806/7a467f08-44a9-11e6-83b4-1925b87544b2.png)

![image](https://cloud.githubusercontent.com/assets/8818542/16673824/8d4dacb6-44a9-11e6-944c-65cf9ab70308.png)

**Comment by prospero238** [comment]
I'm sorry I didn't see this report (I'm trying to maintain an issue list within Jira and don't peruse github issues often).

Are you still receiving this error?
